language: python

matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "3.3"
    - python: "3.4"
    - python: "3.4"
      env: WITHOUT_NUMPY="true"
    - python: "3.5"

before_install:
    - pip --quiet install --use-mirrors numpy

install:
    - source continuous_integration/install.sh

script:
    - make
